Hotfix python version not found issue
Fix the following error raised by github actions:

    Version X was not found in the local cache
    Error: Version X with arch x64 not found

It may be caused by actions/setup-python#555

Consider the users of openalto may still depend on python 3.6, roll back
ubuntu version from `ubuntu-latest` to `ubuntu-20.04`.

Signed-off-by: Jensen Zhang <jingxuan.n.zhang@gmail.com>